SERVER_PORT = 8010
DISCOVERY_PORT = 4010

SERVERS = ['192.168.1.13'] 

HEARTBEAT_INTERVAL = 3  
LEADER_HEARTBEAT_TIMEOUT = 5 

LCR_TIMEOUT = 5  
ELECTION_INTERVAL = 5  

LOG_LEVEL = 'INFO'
LOG_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'